language: python
python:
  - "3.5"

before_install:
  - "apt-get update -y"
  - "apt-get install -y expect"
  - "cd (tests/scripts; ./install-android-sdk;)"

install:
  - "pip install -r requirements.txt"

script:
  - "py.test -s"
